# ===============================
# SERVER CONFIG
# ===============================
server:
  port: 8088
# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base
    username: root
    password: 1234$
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# ===============================
# LOGGING
# ===============================
#server.error.include-stacktrace=on_trace_param
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level [%thread]%logger{115} - %msg%n"
  file:
    name: logs/default.log